export const SEED_RECIPES = [
  { id: '1', name: 'Sheet Pan Chicken Fajitas', category: 'Dinner', tags: ['Quick Dinner', 'Mexican', 'One Pan'], repeatWeeks: 2, notes: '' },
  { id: '2', name: 'Crockpot Pulled Pork', category: 'Dinner', tags: ['Crockpot', 'Comfort Food', 'Leftovers'], repeatWeeks: 3, notes: 'Doubles well' },
  { id: '3', name: 'Spaghetti & Meat Sauce', category: 'Dinner', tags: ['Pasta', 'Comfort Food', 'Italian'], repeatWeeks: 2, notes: '' },
  { id: '4', name: 'Grilled Steak & Asparagus', category: 'Dinner', tags: ['Date Night', 'Grilling', 'High Protein'], repeatWeeks: 4, notes: '' },
  { id: '5', name: 'Taco Tuesday', category: 'Dinner', tags: ['Mexican', 'Quick Dinner', 'Weeknight'], repeatWeeks: 2, notes: '' },
  { id: '6', name: 'Breakfast Burritos', category: 'Breakfast', tags: ['Freezer Meal', 'High Protein'], repeatWeeks: 2, notes: 'Make a batch' },
  { id: '7', name: 'Avocado Toast', category: 'Breakfast', tags: ['Quick Dinner', 'Healthy-ish'], repeatWeeks: 1, notes: '' },
  { id: '8', name: 'Caesar Salad', category: 'Side Dish', tags: ['Salad', 'Low Effort'], repeatWeeks: 2, notes: '' },
  { id: '9', name: 'Roasted Broccoli', category: 'Side Dish', tags: ['Healthy-ish', 'Low Effort'], repeatWeeks: 1, notes: '' },
  { id: '10', name: 'Chocolate Chip Cookies', category: 'Dessert', tags: ['Comfort Food', 'Weekend'], repeatWeeks: 3, notes: '' },
];

export const SEED_INGREDIENTS = [
  { recipeId: '1', name: 'Chicken breast', qty: '1.5 lb', cat: 'Meat & Seafood', staple: false, combine: false, kroger: 'boneless skinless chicken breast' },
  { recipeId: '1', name: 'Bell peppers', qty: '3 mixed', cat: 'Produce', staple: false, combine: true, kroger: 'bell peppers' },
  { recipeId: '1', name: 'Yellow onion', qty: '1 large', cat: 'Produce', staple: false, combine: true, kroger: 'yellow onion' },
  { recipeId: '1', name: 'Flour tortillas', qty: '1 pack', cat: 'Bakery', staple: false, combine: false, kroger: 'flour tortillas' },
  { recipeId: '1', name: 'Fajita seasoning', qty: '1 packet', cat: 'Spices', staple: false, combine: true, kroger: 'fajita seasoning' },
  { recipeId: '1', name: 'Olive oil', qty: '2 tbsp', cat: 'Pantry', staple: true, combine: true, kroger: 'olive oil' },
  { recipeId: '2', name: 'Pork shoulder', qty: '4 lb', cat: 'Meat & Seafood', staple: false, combine: false, kroger: 'pork shoulder boston butt' },
  { recipeId: '2', name: 'BBQ sauce', qty: '1 bottle', cat: 'Pantry', staple: false, combine: false, kroger: "sweet baby ray's bbq sauce" },
  { recipeId: '2', name: 'Hamburger buns', qty: '1 pack', cat: 'Bakery', staple: false, combine: false, kroger: 'hamburger buns' },
  { recipeId: '2', name: 'Yellow onion', qty: '1', cat: 'Produce', staple: false, combine: true, kroger: 'yellow onion' },
  { recipeId: '3', name: 'Ground beef', qty: '1 lb', cat: 'Meat & Seafood', staple: false, combine: false, kroger: '80/20 ground beef' },
  { recipeId: '3', name: 'Spaghetti', qty: '1 box', cat: 'Pantry', staple: false, combine: false, kroger: 'spaghetti pasta' },
  { recipeId: '3', name: 'Marinara sauce', qty: '1 jar', cat: 'Canned Goods', staple: false, combine: false, kroger: "rao's marinara" },
  { recipeId: '3', name: 'Garlic', qty: '4 cloves', cat: 'Produce', staple: false, combine: true, kroger: 'fresh garlic' },
  { recipeId: '3', name: 'Parmesan', qty: '1 wedge', cat: 'Dairy', staple: false, combine: true, kroger: 'parmesan cheese' },
  { recipeId: '4', name: 'Ribeye steak', qty: '2 (12oz)', cat: 'Meat & Seafood', staple: false, combine: false, kroger: 'ribeye steak' },
  { recipeId: '4', name: 'Asparagus', qty: '1 bunch', cat: 'Produce', staple: false, combine: false, kroger: 'fresh asparagus' },
  { recipeId: '5', name: 'Ground beef', qty: '1 lb', cat: 'Meat & Seafood', staple: false, combine: false, kroger: '80/20 ground beef' },
  { recipeId: '5', name: 'Taco shells', qty: '1 box', cat: 'Pantry', staple: false, combine: false, kroger: 'hard taco shells' },
  { recipeId: '5', name: 'Shredded cheese', qty: '1 bag', cat: 'Dairy', staple: false, combine: true, kroger: 'shredded mexican blend' },
  { recipeId: '5', name: 'Lettuce', qty: '1 head', cat: 'Produce', staple: false, combine: true, kroger: 'iceberg lettuce' },
  { recipeId: '5', name: 'Taco seasoning', qty: '1 packet', cat: 'Spices', staple: false, combine: true, kroger: 'taco seasoning' },
  { recipeId: '5', name: 'Salsa', qty: '1 jar', cat: 'Canned Goods', staple: false, combine: true, kroger: 'pace medium salsa' },
  { recipeId: '6', name: 'Eggs', qty: '1 dozen', cat: 'Dairy', staple: false, combine: true, kroger: 'large eggs' },
  { recipeId: '6', name: 'Breakfast sausage', qty: '1 lb', cat: 'Meat & Seafood', staple: false, combine: false, kroger: 'jimmy dean sausage' },
  { recipeId: '6', name: 'Burrito tortillas', qty: '10ct', cat: 'Bakery', staple: false, combine: false, kroger: 'large flour tortillas' },
  { recipeId: '6', name: 'Hash browns', qty: '1 bag', cat: 'Frozen', staple: false, combine: false, kroger: 'frozen hash browns' },
  { recipeId: '6', name: 'Shredded cheese', qty: '1 bag', cat: 'Dairy', staple: false, combine: true, kroger: 'shredded mexican blend' },
  { recipeId: '7', name: 'Avocado', qty: '2', cat: 'Produce', staple: false, combine: true, kroger: 'haas avocado' },
  { recipeId: '7', name: 'Sourdough bread', qty: '1 loaf', cat: 'Bakery', staple: false, combine: false, kroger: 'sourdough bread' },
  { recipeId: '7', name: 'Lemon', qty: '1', cat: 'Produce', staple: false, combine: true, kroger: 'lemon' },
  { recipeId: '8', name: 'Romaine', qty: '2 hearts', cat: 'Produce', staple: false, combine: true, kroger: 'romaine hearts' },
  { recipeId: '8', name: 'Caesar dressing', qty: '1 bottle', cat: 'Pantry', staple: false, combine: true, kroger: 'caesar dressing' },
  { recipeId: '8', name: 'Croutons', qty: '1 bag', cat: 'Bakery', staple: false, combine: true, kroger: 'caesar croutons' },
  { recipeId: '8', name: 'Parmesan', qty: '1 wedge', cat: 'Dairy', staple: false, combine: true, kroger: 'parmesan cheese' },
  { recipeId: '9', name: 'Broccoli', qty: '2 crowns', cat: 'Produce', staple: false, combine: true, kroger: 'broccoli crowns' },
  { recipeId: '10', name: 'Eggs', qty: '2', cat: 'Dairy', staple: false, combine: true, kroger: 'large eggs' },
  { recipeId: '10', name: 'Chocolate chips', qty: '2 cups', cat: 'Pantry', staple: false, combine: true, kroger: 'semi-sweet chocolate chips' },
];

export const CATEGORY_COLORS = {
  'Produce': { dot: '#7BA05B', text: '#3D5A2A' },
  'Meat & Seafood': { dot: '#B85450', text: '#8B3A3A' },
  'Dairy': { dot: '#6B8FB0', text: '#3D5A7A' },
  'Bakery': { dot: '#B89556', text: '#7A5A2D' },
  'Frozen': { dot: '#5B8FB0', text: '#2D5A7A' },
  'Canned Goods': { dot: '#A56B7A', text: '#6B3A4D' },
  'Pantry': { dot: '#A89556', text: '#6B5A2D' },
  'Spices': { dot: '#8B6F4D', text: '#5A4530' },
};
